fixed typo!
aaishikasb/Hacktoberfest-2020 pull request #29
Opened 2020-10-01 13:18 UTC by Nirbhay007

2020-10-01 14:14 UTC, aaishikasb requested changes
The word is meant to be "one", please rectify it. Thanks.

2020-10-01 14:36 UTC, Nirbhay007 commented
Oh sorry, My Bad😅

2020-10-01 19:03 UTC, Nirbhay007 reviewed
done

2020-10-02 04:20 UTC, aaishikasb approved these changes

2020-10-02 04:20 UTC, merged